### ISSUE TITLE
Duplicate Symbols Bug

### ISSUE THREAD

**Issue by UniversalBinary** [sercantutar/infint#4]
There is a problem with the constant definitions at lines 130-132 of the header file.

If InfInt.h is included anywhere in your project more that once building will fail and the linker will complain that there are multiply defined symbols.

This is a show-stopper if you are using InfInt in a large project.

**Comment by alex7071** [comment]
Had the same problem. The only workaround available is to comment out the lines, which means you cannot use some operators without further code changing.
