### ISSUE TITLE
<climits> missing in InfInt.h

### ISSUE THREAD

**Issue by shaklev** [sercantutar/infint#9]
When I include `"InfInt.h"` in my `"main.cpp"` file , i get lots undeclared variables , such as : `ULONG_MAX, ULONG_LONG_MAX, LONG_MAX` etc... 
Including `#include <climits>` in the `"InfInt.h"`  file , solves the issue.

NOTE: I'm using g++ gcc on Fedora24 for compiling

**Comment by melvyniandrag** [comment]
Same issue here. I see limits.h is commented out in the header. Wonder why. Maybe on some platform the header was automatically included or something?
